[
    {
        "TypeofService": "Stafing",
        "VendorID": 1490,
        "GST": "MORGANB0001",
        "VendorName": "Morgan Accessories",
        "ContactPerson": "John",
        "ContactEmail": "john@gmail.com",
        "Mobile": "8976543210",
        "Address": "123 Main street",
        "City": "New York",
        "ZipCode": "10001",
        "State": "New York",
        "Country": "USA",
        "PANCard": "CLMPB2901A"
    },
    {
        "TypeofService": "Stafing",
        "VendorID": 1355,
        "GST": "PENTTECH123",
        "VendorName": "PENT TECH PRIVATE LIMITE",
        "ContactPerson": "Chetan D",
        "ContactEmail": "australiaretailing@gmail.com",
        "Mobile": "330-555-2568",
        "Address": "5th Avenue City",
        "City": "New York",
        "ZipCode": "10005",
        "State": "New York",
        "Country": "USA",
        "PANCard": "CLMPA2901B"
    },
    {
        "TypeofService": "Stafing",
        "VendorID": 1492,
        "GST": "AUSTRALI0001",
        "VendorName": "Australia Retailer",
        "ContactPerson": "Adil",
        "ContactEmail": "advanceshops@gmail.com",
        "Mobile": "612-555-0100",
        "Address": "Oxford Street ",
        "City": "London",
        "ZipCode": "207689",
        "State": "Greater London",
        "Country": "UK",
        "PANCard": "CLMPV2901D"
    },
    {
        "TypeofService": "Stafing",
        "VendorID": 1496,
        "GST": "ADVANCED0001",
        "VendorName": "Advance Shops",
        "ContactPerson": "Naman",
        "ContactEmail": "trikesinclusive@gmail.com",
        "Mobile": "970-555-0118",
        "Address": "Maple Avenue ",
        "City": "New York",
        "ZipCode": "10008",
        "State": "New York",
        "Country": "USA",
        "PANCard": "CLMPJ2901E"
    },
    {
        "TypeofService": "Stafing",
        "VendorID": 1498,
        "GST": "TRIKES0001",
        "VendorName": "Trikes",
        "ContactPerson": "Rohan",
        "ContactEmail": "morganteams@gmail.com",
        "Mobile": "963-555-0134",
        "Address": "5725 Glaze Drive",
        "City": "San Francisco",
        "ZipCode": "10009",
        "State": "Corsica",
        "Country": "France",
        "PANCard": "CLMPU2901F"
    },
    {
        "TypeofService": "Stafing",
        "VendorID": 1504,
        "GST": "CHICAGO0002",
        "VendorName": "Chicago Master",
        "ContactPerson": "Paul",
        "ContactEmail": "accessories@greenwood.com",
        "Mobile": "173-555-0179",
        "Address": "9707 Coldwater Drive, Orlando",
        "City": "Nevada",
        "ZipCode": "10011",
        "State": "Hauts-de-France",
        "Country": "France",
        "PANCard": "CLMPK2901H"
    },
    {
        "TypeofService": "Stafing",
        "VendorID": 1506,
        "GST": "GREENWOO0001",
        "VendorName": "Greenwood Company",
        "ContactPerson": "Caroline",
        "ContactEmail": "enterprises@compete.com",
        "Mobile": "908-555-0159",
        "Address": "1873 Lion Circle",
        "City": "Bothell",
        "ZipCode": "10012",
        "State": "Hauts-de-France",
        "Country": "France",
        "PANCard": "CLMPK2901I"
    }
]